import React, { useState } from 'react'
import { StyleSheet, Text, View, Image, ScrollView, TouchableOpacity, SafeAreaView } from 'react-native';

export default function Scroll() {
    return(
        <View>
            <SafeAreaView>
                <ScrollView>
                    <Text>Scroll
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas, doloribus? Quis sit nam, debitis esse blanditiis molestias qui voluptate sed, provident delectus temporibus assumenda velit perspiciatis quo dolores ex reprehenderit.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae, quis cum. Quisquam, consequuntur repudiandae esse nulla maiores veritatis vitae voluptates in, eum dolorum quis ex quidem est. Ratione, possimus. Dolorem, quasi itaque maxime excepturi quaerat impedit odio. Corporis assumenda laudantium incidunt natus explicabo minus numquam veniam magni, magnam molestias vel dicta eligendi saepe, harum atque! Dolores doloremque nesciunt voluptatum recusandae, reiciendis, tempora incidunt soluta unde rerum consectetur quasi exercitationem iure ea ipsum dolore corporis cum praesentium, blanditiis maiores error magnam! Cumque, sunt labore veritatis quia sequi adipisci libero distinctio accusantium eligendi? Suscipit, eum labore. Est dolorum quaerat non, hic, debitis laboriosam libero magnam accusamus corporis labore, similique porro dolore? Aspernatur aliquam delectus, officiis asperiores ab ea unde debitis totam nulla omnis earum dolores qui doloremque doloribus rerum sint fugiat at rem nostrum.
                    </Text>
                    <Text>Scroll
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas, doloribus? Quis sit nam, debitis esse blanditiis molestias qui voluptate sed, provident delectus temporibus assumenda velit perspiciatis quo dolores ex reprehenderit.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae, quis cum. Quisquam, consequuntur repudiandae esse nulla maiores veritatis vitae voluptates in, eum dolorum quis ex quidem est. Ratione, possimus. Dolorem, quasi itaque maxime excepturi quaerat impedit odio. Corporis assumenda laudantium incidunt natus explicabo minus numquam veniam magni, magnam molestias vel dicta eligendi saepe, harum atque! Dolores doloremque nesciunt voluptatum recusandae, reiciendis, tempora incidunt soluta unde rerum consectetur quasi exercitationem iure ea ipsum dolore corporis cum praesentium, blanditiis maiores error magnam! Cumque, sunt labore veritatis quia sequi adipisci libero distinctio accusantium eligendi? Suscipit, eum labore. Est dolorum quaerat non, hic, debitis laboriosam libero magnam accusamus corporis labore, similique porro dolore? Aspernatur aliquam delectus, officiis asperiores ab ea unde debitis totam nulla omnis earum dolores qui doloremque doloribus rerum sint fugiat at rem nostrum.
                    </Text>
                    <Text>Scroll
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas, doloribus? Quis sit nam, debitis esse blanditiis molestias qui voluptate sed, provident delectus temporibus assumenda velit perspiciatis quo dolores ex reprehenderit.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae, quis cum. Quisquam, consequuntur repudiandae esse nulla maiores veritatis vitae voluptates in, eum dolorum quis ex quidem est. Ratione, possimus. Dolorem, quasi itaque maxime excepturi quaerat impedit odio. Corporis assumenda laudantium incidunt natus explicabo minus numquam veniam magni, magnam molestias vel dicta eligendi saepe, harum atque! Dolores doloremque nesciunt voluptatum recusandae, reiciendis, tempora incidunt soluta unde rerum consectetur quasi exercitationem iure ea ipsum dolore corporis cum praesentium, blanditiis maiores error magnam! Cumque, sunt labore veritatis quia sequi adipisci libero distinctio accusantium eligendi? Suscipit, eum labore. Est dolorum quaerat non, hic, debitis laboriosam libero magnam accusamus corporis labore, similique porro dolore? Aspernatur aliquam delectus, officiis asperiores ab ea unde debitis totam nulla omnis earum dolores qui doloremque doloribus rerum sint fugiat at rem nostrum.
                    </Text>
                    <Text>Scroll
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas, doloribus? Quis sit nam, debitis esse blanditiis molestias qui voluptate sed, provident delectus temporibus assumenda velit perspiciatis quo dolores ex reprehenderit.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae, quis cum. Quisquam, consequuntur repudiandae esse nulla maiores veritatis vitae voluptates in, eum dolorum quis ex quidem est. Ratione, possimus. Dolorem, quasi itaque maxime excepturi quaerat impedit odio. Corporis assumenda laudantium incidunt natus explicabo minus numquam veniam magni, magnam molestias vel dicta eligendi saepe, harum atque! Dolores doloremque nesciunt voluptatum recusandae, reiciendis, tempora incidunt soluta unde rerum consectetur quasi exercitationem iure ea ipsum dolore corporis cum praesentium, blanditiis maiores error magnam! Cumque, sunt labore veritatis quia sequi adipisci libero distinctio accusantium eligendi? Suscipit, eum labore. Est dolorum quaerat non, hic, debitis laboriosam libero magnam accusamus corporis labore, similique porro dolore? Aspernatur aliquam delectus, officiis asperiores ab ea unde debitis totam nulla omnis earum dolores qui doloremque doloribus rerum sint fugiat at rem nostrum.
                    </Text>
                    <Text>Scroll
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas, doloribus? Quis sit nam, debitis esse blanditiis molestias qui voluptate sed, provident delectus temporibus assumenda velit perspiciatis quo dolores ex reprehenderit.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae, quis cum. Quisquam, consequuntur repudiandae esse nulla maiores veritatis vitae voluptates in, eum dolorum quis ex quidem est. Ratione, possimus. Dolorem, quasi itaque maxime excepturi quaerat impedit odio. Corporis assumenda laudantium incidunt natus explicabo minus numquam veniam magni, magnam molestias vel dicta eligendi saepe, harum atque! Dolores doloremque nesciunt voluptatum recusandae, reiciendis, tempora incidunt soluta unde rerum consectetur quasi exercitationem iure ea ipsum dolore corporis cum praesentium, blanditiis maiores error magnam! Cumque, sunt labore veritatis quia sequi adipisci libero distinctio accusantium eligendi? Suscipit, eum labore. Est dolorum quaerat non, hic, debitis laboriosam libero magnam accusamus corporis labore, similique porro dolore? Aspernatur aliquam delectus, officiis asperiores ab ea unde debitis totam nulla omnis earum dolores qui doloremque doloribus rerum sint fugiat at rem nostrum.
                    </Text>
                </ScrollView>
            </SafeAreaView>
        </View>
    )
}